openshift/ocm-agent

- Makefile
- build/Dockerfile
- build/bin/entrypoint
- build/bin/user_setup
- build/build_push.sh
- cmd/ocm-agent/main.go
- go.mod
- go.sum
- hack/dummy.go
- hack/test.sh
This is basic skeleton for ocm-agent webserver.
https://issues.redhat.com/browse/OSD-8947
> [OSD-8947] ocm-agent skeleton code

- Makefile
- OWNERS
Minor fix
- Fix Makefile for `make serve`
- Add user `jwai7` to the reviewers list
> Fix Makefile and Add jwai7 to the reviewers list

- build/build_deploy.sh
Feature
Adds a script which will be used in building via AppSRE pipelines
[OSD-8939](https://issues.redhat.com/browse/OSD-8939)
> Add build_deploy.sh for app-sre onboarding

- pkg/cli/serve/serve.go
Remove duplicate healthcheck routes
_(cleanup)_
_Fixes #_
> Remove duplicate healthcheck routes

- docs/CLI-usage.md
- docs/FAQ.md
- docs/design.md
- docs/development.md
- docs/testing.md
Signed-off-by: Aniket Joshi <anjoshi@redhat.com>
Documentation
This PR improves OCM Agent docs by adding multiple files covering different topics.
[OSD-10013](https://issues.redhat.com/browse/OSD-10013)
> OSD-10013 Improve OA docs

- pkg/metrics/metrics.go
Signed-off-by: Aniket Joshi <anjoshi@redhat.com>
Refactor
This PR change refactors existing logic of ocm_agent_requests_total metric to exclude unnecessary path requests count for more clarity. 
[OSD-10204](https://issues.redhat.com/browse/OSD-10204)
_Fixes #_
> OSD-10204 Refactor ocm_agent_requests_total metric

- go.mod
- go.sum
- pkg/handlers/webhookreceiver.go
_(refactor)_
the type managedNotification updated in ocm-agent-operator, pull the changes to ocm-agent
_Fixes #_
> update the dependency ocm-agent-operator

- pkg/handlers/webhookreceiver.go
_(refactor)_
follow up PR for https://github.com/openshift/ocm-agent/pull/19
fix the functions which are using name template
_Fixes #_
> update the functions which are using name template

- go.mod
- go.sum
- pkg/handlers/webhookreceiver.go
_feature_
Update the managednotification status based on the status transition
_Fixes #OSD-10340_
> [OSD-10340] update the status for managed notification object

- pkg/handlers/webhookreceiver.go
_(bug)_
Fix the broken send Service Log logic
_Fixes #_
> send SL based on alert firing status

- pkg/consts/test/test.go
- pkg/handlers/webhookreceiver.go
- pkg/handlers/webhookreceiver_test.go
_(test)_
More tests for webhookreceiver
_Fixes #_ [OSD-10339](https://issues.redhat.com/browse/OSD-10339)
- Adding tests for `updateNotificationStatus()`
- Adding tests for `processAlert()`
> Adding more tests for webhookreceiver

- pkg/handlers/webhookreceiver.go
_feature_
Handle the ocm response and return corresponding errors
_Fixes #OSD-10627_
> [OSD-10627] handle the ocm response

- pkg/handlers/webhookreceiver.go
- pkg/handlers/webhookreceiver_test.go
Test
Adds a couple of small tests on the back of [OSD-10627](https://issues.redhat.com/browse/OSD-10627) / PR #32 
[OSD-10627](https://issues.redhat.com/browse/OSD-10627)
> OSD-10627 Add response checker tests

- pkg/cli/serve/serve.go
- pkg/handlers/webhookreceiver.go
- pkg/k8s/client.go
_(lint)_
This PR fixes some of the lint errors reported by `make lint`.
_Fixes #_ [OSD-10784](https://issues.redhat.com/browse/OSD-10784)
- This PR helps in fixing test for [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27514/rehearse-27514-pull-ci-openshift-ocm-agent-master-lint/1511178358208073728).
> Fixing lint issues

- docs/testing.md
_(doc)_
This is a test PR to check if the test and lint jobs are run as part of the PR or not as presubmit jobs.
_Fixes #_ [OSD-10784](https://issues.redhat.com/browse/OSD-10784)
> Adding small commit to test lint and test jobs

- OWNERS
Minor fix
- add user `rendhalver` to the reviewers list
_Fixes [OSD-10696](https://issues.redhat.com/browse/OSD-10696)
> OSD-10696 add myself to owners file

- pkg/cli/serve/serve.go
Bug
Fixes an issue that was preventing the main web server from being served out.
> Fix bug preventing serve of webhook

- docs/metrics.md
_(documentation)_
Adding the description for each of the metric
_Fixes #OSD-10624_
> [OSD-10624] add the doc for metrics

- .gitignore
- test/README.md
- test/build-and-run.sh
- test/manifests/sre-managed-notifications.yaml
- test/template-alert.json
- test/test-alerts.sh
- test/util/create-alert.sh
- test/util/post-alert.sh
- test/util/servicelog.sh
_(test)_
This PR adds local scripts used for integration testing purposes.
_Fixes #_ [OSD-10781](https://issues.redhat.com/browse/OSD-10781)
> Adding local scripts for integration testing

- docs/metrics.md
- pkg/handlers/webhookreceiver.go
- pkg/handlers/webhookreceiver_test.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
_(/feature/)_
Add a new metric which to be exposed to observatorium 
_Fixes #OSD-12436_
> [OSD-12436]add new metric for total SL count based on the managedNotification status

- OWNERS
_(Add approver)_
Adding myself as an approver as well in addition to existing approvers.
> Adding ravitri as approver

- OWNERS
Adding Abhishek and Wenqi as approvers.
> Adding Abhishek and Wenqi as approvers for OAO

- pkg/cli/serve/serve.go
bug
Fleet-mode should not rely on the internal cluster id. This PR splits the logic for fleet mode and non-fleet mode to change this.
_Fixes #_
> Fix: fleet mode should not rely on a cluster-id flag

- build/Dockerfile
Need to update 
https://issues.redhat.com/browse/OSD-25894
Updating 
- [ x ] Tested latest changes against a cluster
- [ n/a ] Ran `make generate` command locally to validate code changes
- [ n/a ] Included documentation changes with PR
> Upgrade image from Rhel8/Ubi8 to Rhel9/ubi9.

- build/Dockerfile
This reverts commit 1620c0a5087422a32399c5f5ea96115243898ef6.
_(bug/feature/cleanup/documentation/test/refactor)_
_Fixes #_
> Revert "Upgrade image from Rhel8/Ubi8 to Rhel9/ubi9. (#116)"

- OWNERS
Closes [OSD-26937](https://issues.redhat.com//browse/OSD-26937)
> OSD-26937: Removing Pete Brown from reviewers

- OWNERS
remove Wenqi from the owner as he moved to LP-SRE
> remove Wenqi from the owner

- .github/dependabot.yml
> Schedule dependabot monthly

- hack/00-ocm-agent.selectorsyncset.yaml.tmpl
_refactor_
- Updates the selector to be based on sector rather than regions
_Fixes #[OSD-30101](https://issues.redhat.com//browse/OSD-30101)_
> OSD-30101: refactor(Update SSS Selector for regional OCM)

- hack/00-ocm-agent.selectorsyncset.yaml.tmpl
_refactor_
Updates the base OCM URL for SGP MC Clusters
_Fixes #_
> OSD-30101: refactor(rename OCM base URl for SGP MC Clusters)

- pkg/httpchecker/httpchecker_suite_test.go
- pkg/httpchecker/reattemp_test.go
- pkg/httpchecker/urlavailabilitychecker_test.go
unit tests for pkg/httpchecker in ocm-agent repo.
Improve Code Coverage 
[SREP-908](https://issues.redhat.com//browse/SREP-908)
> SREP-908 [unit tests for pkg/httpchecker]
