openshift/ocm-agent

Makefile
Bug
The `build-push` Make target was using an invalid transport means of `container-storage`, it should be `containers-storage`.
=> Correct skopeo argument in build-push target

go.mod, go.sum, pkg/cli/serve/serve.go, pkg/config/config.go
Feature
OCM Agent needs to know the cluster ID; it's currently getting that injected into the ConfigMap used to supply config to the pod; now we need to make the agent aware that it has to read that config.
Additionally, `viper` has been introduced to enable easier retrieval of app configuration items, this will make subsequent tickets a lot easier to deal with when they need to access the application's config. eg.
```
viper.Get(config.SomeConfigKey)
```
[OSD-10226](https://issues.redhat.com/browse/OSD-10226)
=> OSD-10226 Add cluster ID and support viper

pkg/consts/test/test.go, pkg/handlers/webhookreceiver.go, pkg/handlers/webhookreceiver_test.go
Feature
Proposed implementation of [OSD-10339](https://issues.redhat.com/browse/OSD-10339) to not send a notification if it has already been sent within the do-not-resend window. Needs a bunch of tests still to verify correctness.
[OSD-10339](https://issues.redhat.com/browse/OSD-10339)
=> OSD-10339 Do not send a notification if within the window

hack/00-ocm-agent.selectorsyncset.yaml.tmpl
Feature
Adds a SelectorSyncSet template required if we want to onboard `ocm-agent` promotions into `app-interface`
[OSD-10122](https://issues.redhat.com/browse/OSD-10122)
=> OSD-10122 Add SelectorSyncSet template

go.mod, go.sum, pkg/handlers/webhookreceiver.go, pkg/handlers/webhookreceiver_test.go
_feature_
The alertmanager webhook receiver should be able to handle both the alerting and resolved alerts
And update the status correspondingly
Fixes #[OSD-10225](https://issues.redhat.com/browse/OSD-10225)
=> [OSD-10225] handle the service log sending for resolved alerts

hack/00-ocm-agent.selectorsyncset.yaml.tmpl
Bug
The `SelectorSyncSet` template needs to define `OCM_BASE_URL` as a parameter in order for it to be replaced.
=> OSD-10122 Fix the SSS template

pkg/handlers/webhookreceiver.go
Cleanup
Minor change. Improves the formatting of the alert data by ensuring that the struct's fieldnames are specified. It's not perfect, but it makes the log slightly more interpretable to know what fields mean what.
Goes from this:
```
alert="{firing map[alertname:AnotherWatchdogManagedNotificationSRE alertstate:firing namespace:openshift-monitoring openshift_io_alert_source:platform prometheus:openshift-monitoring/k8s send_managed_notification:true severity:info] map[description:test] 2022-03-13 04:45:16 +0000 UTC 0001-01-01 00:00:00 +0000 UTC https://blahblah }"
```
to this:
```
alert="{Status:firing Labels:map[alertname:AnotherWatchdogManagedNotificationSRE alertstate:firing namespace:openshift-monitoring openshift_io_alert_source:platform prometheus:openshift-monitoring/k8s …
```
=> More understandable formatting of alert data in logs

build/Dockerfile
_(bug)_
This PR updates the base docker image from `ubi-minimal` to `ubi-micro` such that the number of CVE reported by Clair security scan in Quay reports no/minimal vulnerabilities.
_Fixes #_ [OSD-10499](https://issues.redhat.com/browse/OSD-10499)
- Update to latest `ubi-minimal` image version [8.5-240](https://catalog.redhat.com/software/containers/ubi8-minimal/5c64772edd19c77a158ea216?container-tabs=overview) did not work and it still had 2 CVEs open.
- Thus, the base image was changed to `ubi-micro` with latest version [8.5-833](https://catalog.redhat.com/software/containers/ubi8/ubi-micro/5ff3f50a831939b08d1b832a?container-tabs=overview). The repo image with this image showed GREEN health as seen in [image](https://quay.io/repository/travi/ocm-agent/manifest/sha256:cb22ae2ef8dda5445c …
=> Changing image to ubi-micro to address CVE

pkg/metrics/metrics.go, pkg/metrics/metrics_suite_test.go, pkg/metrics/metrics_test.go
Test
Metrics! Tests! Everybody loves them. This PR adds tests for our metrics to make sure they're being set properly when the middleware handler is called, and when our helper functions are called.
As part of writing these tests I noticed we had a slightly brittle piece of code when getting the gorilla mux route in the middleware handler. If the `mux.CurrentRoute(r)` were to ever return nil (which it _can_) that would cause a panic as it is not checked. So that is now made safer.
[OSD-10354](https://issues.redhat.com//browse/OSD-10354)
=> OSD-10354 Add metrics test suite

.golangci.yml
feature
Enables gosec linting for ocm agent.
`golangci-lint` will include a `.golangci.yml` file if it exists in the repository.
This just adds that file and enables gosec in our existing lint check.
Fixes [OSD-11459](https://issues.redhat.com//browse/OSD-11459)
=> OSD-11456 enable gosec linting

pkg/cli/serve/serve.go, pkg/logging/logging.go
_(refactor)_
This PR refactors logging in the `serve.go` file such that it imports logging configuration from a separate package called `logging`.
_Fixes #_ [OSD-10012](https://issues.redhat.com/browse/OSD-10012)
* For now, only serve.go has been considered for refactoring.
* The default log level is maintained to be `Info` and is set to `Debug` level if the CLI passes `-d true`. Both options work as expected.
=> Refactoring logging to move to separate package

Makefile, cmd/ocm-agent/fips.go
Feature
Ensure that `ocm-agent` runs with FIPS enabled so that it is consistent with other OSD operators.
=> Enable FIPS

Makefile
Feature
MCVW must be built with CGO_ENABLED=1 (and based on ubi-minimal) to be FIPS compliant
https://issues.redhat.com/browse/OSD-17665
=> CGO_ENABLED=1 to enable FIPS

pkg/cli/serve/config.go, pkg/cli/serve/serve.go, pkg/config/config.go, pkg/handlers/webhookreceiver.go, pkg/ocm/connection.go
_(bug/feature/cleanup/documentation/test/refactor)_
Allows users to pass in multiple services into ocm-agent - instead of just 'service_logs'.
I.e.
`ocm agent serve --services="service_logs,clusters"`
_Fixes #_
=> Make services CLI flag a list

docs/metrics.md, pkg/consts/test/test.go, pkg/handlers/helper.go, pkg/handlers/mocks/service_logs.go, pkg/handlers/service_logs.go, pkg/handlers/service_logs_test.go, pkg/handlers/webhookreceiver.go, pkg/handlers/webhookreceiver_test.go, pkg/handlers/webhookrhobsreceiver.go, pkg/handlers/webhookrhobsreceiver_test.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
Place holders are replaced with the alert labels & annotations in the service log to generate
_feature_
This PR allows to use alert labels & annotations in the service logs sent by `ocm-agent`
_Implements_ [OSD-19689](https://issues.redhat.com//browse/OSD-19689)
=> OSD-19689: implementing a place holder feature for notifications

pkg/cli/serve/serve.go, pkg/handlers/cluster.go, pkg/handlers/cluster_test.go, pkg/handlers/handlers_common.go, pkg/handlers/handlers_test.go, pkg/handlers/upgrade_policies.go, pkg/handlers/upgrade_policies_test.go
_(bug/feature/cleanup/documentation/test/refactor)_
Feature
This PR implements a cluster handler which can get the `*cmv1.Cluster` object from OCM.
- It adds an endpoint /my_cluster . `GET /my_cluster` will return the `Cluster` object of the current cluster.
- Add tests for the cluster handler.
- Move some existing functions from `upgrade_policies.go` and `upgrade_policies_test.go` to `handlers_common.go` and `handlers_test.go` for reuse.
https://issues.redhat.com/browse/OSD-19232
_Fixes #_
=> OSD-19232 add cluster handler to get cluster object

hack/00-ocm-agent.selectorsyncset.yaml.tmpl
_(feature)_
To allow MUO and other OCM agent consumers to use the `clusters_mgmt` endpoint, we need to make sure that its manager, the OCM agent operator, has enabled the new endpoint.
This enables the `/clusters` endpoint for all ROSA/OSD clusters, so that they can begin to use it OCM agent as an endpoint proxy. 
https://github.com/openshift/managed-cluster-config/pull/1948 depends on it. 
_Fixes #_
https://issues.redhat.com/browse/OSD-19765
=> Add clusters_mgmt service on all ocm-agent services

hack/00-ocm-agent.selectorsyncset.yaml.tmpl
_(feature)_
Increase the replicas of the ocm-agent to make it Highly Available. It interdependent with the [PR-102](https://github.com/openshift/ocm-agent-operator/pull/102)
https://issues.redhat.com/browse/OSD-19745
=> [OSD-19745] - Increase the replicas of the ocm-agent pod as part of the HA task

pkg/handlers/cluster.go, pkg/handlers/cluster_test.go, pkg/handlers/handlers_common.go, pkg/handlers/handlers_test.go, pkg/handlers/upgrade_policies.go, pkg/handlers/upgrade_policies_test.go
_(bug)_
When testing, we discovered that we are missing the "X-Operation-Id" header from all responses to the new '/clusters' and '/upgrade_policies' endpoints. This means that any non 200 request to consumers of the new OCM Agent API will not be able to track down the source of their bug in the OCM audit logs.
This PR includes "X-Operation-ID" header on all responses from new 'endpoint proxy' routes.
_Fixes #_
https://issues.redhat.com/browse/OSD-20054
=> Add operation ID header to all outbound requests

docs/metrics.md, pkg/cli/serve/serve.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
this PR is a proposal to add a new metric: `ocm_agent_pull_secret_invalid`.
with this PR, we will have a metric on every OSD/ROSA cluster that will allow us to add an alert such as https://github.com/openshift/managed-cluster-config/pull/1847 to be used to prevent other alerts such as in https://github.com/openshift/managed-cluster-config/pull/1848.
https://issues.redhat.com/browse/OSD-18372
=> add pull secret invalid metric

hack/00-ocm-agent.selectorsyncset.yaml.tmpl
cleanup
unused field
the field is not present in the SSS object on the cluster. here is some output from qontract-reconcile when trying to deploy:
```
[DEBUG] [DRY-RUN] [three_way_diff_strategy.py:three_way_diff_using_hash:150] - Desired and Current objects differ -> Apply: [{'op': 'add', 'path': '/status', 'value': {}}]
```
_Fixes #_
=> remove status field from openshift template

pkg/handlers/helper.go, test/template-alert-fleet-notification.json
bug
`source` has been modified for management clusters, it's now `MC` instead of `HCP`. We should just check if a source label is present as part of the fleet-mode precheck instead of checking the value.
Error example:
```
time="2024-01-30T10:42:49Z" level=error msg="fleet mode alert has no valid source" alertname=0xc000711530
```
_Fixes #_
=> Fix: source label verification for fleet-mode

.github/dependabot.yml, docs/maintenance.md
_(bug/feature/cleanup/documentation/test/refactor)_
Repo enhancement: Automatically bump the base image 
Using Dependabot to automatically bump the base image so we can reduce the manual effort for dependency maintenance.
[_Fixes OSD-20180](https://issues.redhat.com/browse/OSD-20180)
=> Osd 20180 adding dependabot to automatically bump the base image

pkg/consts/test/test.go, pkg/handlers/webhookrhobsreceiver.go, pkg/handlers/webhookrhobsreceiver_test.go, test/test-fleet-mode-alerts.sh
bug
Fixes race condition in fleet mode alert handling. We were not handling conflicts on kube resource updates.
Fixes [OSD-20662](https://issues.redhat.com//browse/OSD-20662)
=> Fix(OSD-20662): race condition in fleet mode alert handling

pkg/handlers/webhookrhobsreceiver.go, pkg/handlers/webhookrhobsreceiver_test.go, test/test-fleet-mode-alerts.sh
**Note:** **this is a branch off https://github.com/openshift/ocm-agent/pull/82 - once PR 82 is merged, the diff here will be much smaller.** 
bug
When alertmanager restarts, all alerts are resent. This PR adds a check to make sure we don't send limited support if it's already active. No changes to service logs.
I also included an E2E test for this.
Fixes [OSD-20857](https://issues.redhat.com//browse/OSD-20857)
=> fix(OSD-20857): resend LS only when resolved

pkg/handlers/helper.go, pkg/handlers/webhookrhobsreceiver.go, pkg/handlers/webhookrhobsreceiver_test.go, test/test-fleet-mode-alerts.sh
bug
**The bug:** 
- with the [latest fix of a nil ptr deref](https://github.com/openshift/ocm-agent-operator/pull/111) in `ocm-agent-operator`, recorditems with a `nil` `lastUpdatedTimestamp` are automatically garbage collected
- we currently need to pre-create recorditems for the `CanBeSent()` function, but the timestamp isn't set
**Result:** the recorditems we create are instantly garbage collected by ocm-agent-operator
**The fix:**
`FiringCanBeSent()` defined in `ocm-agent-operator` (API) requires a `managedfleetnotificationrecord` to exist: https://github.com/openshift/ocm-agent-operator/blob/e0178327b55ced0475e276c147e7b73b7c4cbfe1/api/v1alpha1/managedfleetnotificationrecord_types.go#L145
Due to this, we needed to create it before the check. 
This PR re-implements `firingCanBeSent()` …
=> Fix: CanBeSent does not rely on existing object

pkg/handlers/webhookrhobsreceiver.go, test/test-fleet-mode-alerts.sh, test/util/oc.sh
test
This PR adds more tests for the previous PR https://github.com/openshift/ocm-agent/pull/89. These tests would have caught the unwanted garbage collection of recorditems before it made it to prod.
_Fixes #_
=> OSD-20982: add check for the recorditem states to integration tests

hack/00-ocm-agent.selectorsyncset.yaml.tmpl
_(feature)_
This pull request demonstrates how to deploy OCM agent in fleet mode on management clusters. 
_Fixes #_
https://issues.redhat.com/browse/OSD-20371
Spike doc explaining how to test this: https://docs.google.com/document/d/1nw4XeEftcq67M9Jg9ljJd5W09y-8mE05KHdXxgk5QOk/edit
=> Add OcmAgent selectorsyncset for management clusters

pkg/consts/test/test.go, pkg/handlers/helper.go, pkg/handlers/helper_test.go
_(bug)_
We are validating the alert with label before proceed it with the ocm-agent service log sending.
There was a `source` label when the alerts are handled by the rhobs, but the field is not there when we move the alert handling to the obo stack running on the management cluster.
The existing validator with alert label _id and _mc_id should be able to indicate the alert is valid.
Fixes #[OSD-25042](https://issues.redhat.com//browse/OSD-25042)
=> remove the validating for source field for fleet mode alerts

build/Dockerfile
_maintenance_
Based on the existing supported versions of OCP, https://github.com/openshift/ocm-agent should atleast support Go 1.22 ahead till version 4.17. 
_Fixes #OSD-25318_
=> Updating the go version to 1.22 in the docker file

Makefile, build/Dockerfile, pkg/ocm/ocm.go
_(bug)_
Raising this PR to fix the base image for ocm-agent to not use Centos base image but aligning it to use boilerplate image. Without this fix, ocm-agent has failure like:
```shell
2024-09-30T04:12:24.317367291+00:00 stderr F ocm-agent: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ocm-agent)
2024-09-30T04:12:24.317367291+00:00 stderr F ocm-agent: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ocm-agent)
```
Thanks @tkong-redhat and @a7vicky to figure out the issue :+1:
=> Updating base image to match boilerplate for Go 1.22

build/Dockerfile
_(bug)_
Currently there is a critical issue in the base image which leads ocm-agent failed to start.
We need to revert the base image so ocm-agent could start properly and make the cluster back to normal status.
[OSD-25814](https://issues.redhat.com/browse/OSD-25814)
_Fixes #_
=> OSD-25814 revert base image because of critical issue in the base image

build/Dockerfile
_(bug)_
```
panic: opensslcrypto: can't initialize OpenSSL : openssl: can't retrieve OpenSSL version
goroutine 1 [running]:
crypto/internal/backend.init.0()
/usr/local/go/src/crypto/internal/backend/openssl.go:65 +0x299
```
Change the base image having openssl pkg
_Fixes #_[OSD-30088](https://issues.redhat.com/browse/OSD-30088)
=> change base image to ubi8-minimal:8.10-1255

hack/00-ocm-agent.selectorsyncset.yaml.tmpl
This PR updates the SSS for ocm agent deployed on MC Clusters to be able to use different OCM URL for Singapore MC Clusters
_refactor_
_Fixes #[OSD-30101](https://issues.redhat.com//browse/OSD-30101)_
=> OSD-30101: refactor - Update SSS for ocm agents on MC to use different URL for Singapore
